### ISSUE TITLE
output:LIFENESS FAIL

### ISSUE THREAD

**Issue by herokarimpoor** [juan-csv/face_liveness_detection-Anti-spoofing#4]
hi 
thank for you
Each time output test:LIFENESS FAIL
And I do all the movements correctly

How can you help me?
thank you

**Comment by juan-csv** [comment]
Hi, I need more information to know what happens, for now I recommend that you observe the result of the detection of emotion, profile, blinking etc, for this go to the script face_anti_spoofing.py

and on line 47 in out_model = f_liveness_detection.detect_liveness (im, COUNTER, TOTAL_0)
add a print (out_model), proceed to run the script and see the result of the detected

**Comment by herokarimpoor** [comment]
Thank you for your answer
